import uuid
import json

VilleRecords =[
             {'id_profession' : '1', 'profession' : 'Médecin', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '2', 'profession' : 'Enseignant', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '3', 'profession' : 'Ingénieur', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '4', 'profession' : 'Avocat', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '5', 'profession' : 'Artiste', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '6', 'profession' : 'Policier', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '7', 'profession' : 'Pompier', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '8', 'profession' : 'Infirmière', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '9', 'profession' : 'Agriculteur', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '10', 'profession' : 'Comptable', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '11', 'profession' : 'Électricien', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '12', 'profession' : 'Plombier', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '13', 'profession' : 'Journaliste', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '14', 'profession' : 'Designer', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '15', 'profession' : 'Chercheur', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '16', 'profession' : 'Chef cuisinier', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '17', 'profession' : 'Chauffeur de taxi', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '18', 'profession' : 'Entrepreneur', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '19', 'profession' : 'Acteur', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '20', 'profession' : 'Boulanger', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '21', 'profession' : 'Astronaute', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '22', 'profession' : 'Architecte', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '23', 'profession' : 'Banquier', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '24', 'profession' : 'Bibliothécaire', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '25', 'profession' : 'Boucher', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '26', 'profession' : 'Bijoutier', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '27', 'profession' : 'Chirurgien', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '28', 'profession' : 'Couvreur', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '29', 'profession' : 'Coiffeur', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '30', 'profession' : 'Dentiste', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '31', 'profession' : 'Économiste', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '32', 'profession' : 'Facteur', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '33', 'profession' : 'Fermier', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '34', 'profession' : 'Fleuriste', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '35', 'profession' : 'Garde forestier', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '36', 'profession' : 'Géologue', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '37', 'profession' : 'Graphiste', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '38', 'profession' : 'Guide touristique', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '39', 'profession' : 'Historien', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '40', 'profession' : 'Horloger', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '41', 'profession' : 'Infirmier praticien', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '42', 'profession' : 'Inspecteur de police', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '43', 'profession' : 'Juge', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '44', 'profession' : 'Kinésithérapeute', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '45', 'profession' : 'Libraire', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '46', 'profession' : 'Mécanicien automobile', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '47', 'profession' : 'Négociant en bourse', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '48', 'profession' : 'Orthophoniste', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '49', 'profession' : 'Pharmacien', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '50', 'profession' : 'Pilote de ligne', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '51', 'profession' : 'Psychologue', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '52', 'profession' : 'Radiologiste', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '53', 'profession' : 'Sapeur-pompier', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '54', 'profession' : 'Scénariste', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '55', 'profession' : 'Sculpteur', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '56', 'profession' : 'Serrurier', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '57', 'profession' : 'Tailleur', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '58', 'profession' : 'Traducteur', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '59', 'profession' : 'Urbaniste', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '60', 'profession' : 'Vétérinaire', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '61', 'profession' : 'Zoologiste', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '62', 'profession' : 'Agent immobilier', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '63', 'profession' : 'Agriculteur biologique', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '64', 'profession' : 'Animateur radio', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '65', 'profession' : 'Antiquaire', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '66', 'profession' : 'Archéologue', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '67', 'profession' : 'Astronome', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '68', 'profession' : 'Bijoutier', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '69', 'profession' : 'Boulanger-pâtissier', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '70', 'profession' : 'Bûcheron', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '71', 'profession' : 'Chanteur', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '72', 'profession' : 'Chauffeur de bus', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '73', 'profession' : 'Chercheur en biologie', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '74', 'profession' : 'Chimiste', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '75', 'profession' : 'Coach sportif', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '76', 'profession' : 'Conducteur de train', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '77', 'profession' : 'Conseiller financier', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '78', 'profession' : 'Cuisinier', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '79', 'profession' : 'Déménageur', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '80', 'profession' : 'Ébéniste', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '81', 'profession' : 'Économiste', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '82', 'profession' : 'Électricien automobile', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '83', 'profession' : 'Électricien bâtiment', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '84', 'profession' : 'Électricien industriel', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '85', 'profession' : 'Fleuriste', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '86', 'profession' : 'Garde-côte', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '87', 'profession' : 'Géomètre', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '88', 'profession' : 'Géophysicien', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '89', 'profession' : 'Guide de montagne', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '90', 'profession' : 'Ingénieur en aéronautique', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '91', 'profession' : 'Ingénieur en informatique', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '92', 'profession' : 'Jardinier paysagiste', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '93', 'profession' : 'Joallier', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '94', 'profession' : 'Journaliste sportif', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '95', 'profession' : 'Libraire', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '96', 'profession' : 'Maçon', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '97', 'profession' : 'Mécanicien moto', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '98', 'profession' : 'Météorologue', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '99', 'profession' : 'Musicien', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '100', 'profession' : 'Océanographe', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '101', 'profession' : 'Optométriste', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '102', 'profession' : 'Orthopédiste', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '103', 'profession' : 'Pâtissier', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '104', 'profession' : 'Pharmacien d\'officine', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '105', 'profession' : 'Photographe', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '106', 'profession' : 'Physicien', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '107', 'profession' : 'Pilote de chasse', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '108', 'profession' : 'Plâtrier', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '109', 'profession' : 'Plongeur sous-marin', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '110', 'profession' : 'Podologue', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '111', 'profession' : 'Poissonnier', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '112', 'profession' : 'Policier scientifique', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '113', 'profession' : 'Professeur d\'université', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '114', 'profession' : 'Psychiatre', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '115', 'profession' : 'Radiologue', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '116', 'profession' : 'Réalisateur de film', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '117', 'profession' : 'Sculpteur sur bois', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '118', 'profession' : 'Skipper', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '119', 'profession' : 'Sociologue', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '120', 'profession' : 'Sommelier', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '121', 'profession' : 'Soudeur', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '122', 'profession' : 'Styliste', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '123', 'profession' : 'Tailleur de pierre', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '124', 'profession' : 'Taxidermiste', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '125', 'profession' : 'Tôlier', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '126', 'profession' : 'Urbaniste', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '127', 'profession' : 'Vendeur de voitures', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '128', 'profession' : 'Viticulteur', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '129', 'profession' : 'Zoologiste marin', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '130', 'profession' : 'Acrobate', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '131', 'profession' : 'Aide-soignant', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '132', 'profession' : 'Archiviste', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '133', 'profession' : 'Astronome amateur', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '134', 'profession' : 'Bibliothécaire scolaire', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '135', 'profession' : 'Boucher-charcutier', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '136', 'profession' : 'Cancérologue', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '137', 'profession' : 'Charpentier', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '138', 'profession' : 'Chef de projet informatique', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '139', 'profession' : 'Chef de rang', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '140', 'profession' : 'Chef étoilé', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '141', 'profession' : 'Chiropraticien', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '142', 'profession' : 'Chorégraphe', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '143', 'profession' : 'Cinéaste', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '144', 'profession' : 'Comédien', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '145', 'profession' : 'Consultant en marketing', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '146', 'profession' : 'Danseur', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '147', 'profession' : 'Dentiste pédiatrique', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '148', 'profession' : 'Designer d\'intérieur', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '149', 'profession' : 'Éboueur', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '150', 'profession' : 'Écrivain', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '151', 'profession' : 'Électricien de maintenance', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '152', 'profession' : 'Électricien naval', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '153', 'profession' : 'Électricien résidentiel', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '154', 'profession' : 'Électronicien', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '155', 'profession' : 'Facteur d\'instruments de musique', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '156', 'profession' : 'Fleuriste en ligne', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '157', 'profession' : 'Frigoriste', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '158', 'profession' : 'Garde-pêche', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '159', 'profession' : 'Géophysicien marin', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '160', 'profession' : 'Guide de safari', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '161', 'profession' : 'Hydrogéologue', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '162', 'profession' : 'Ingénieur aérospatial', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '163', 'profession' : 'Ingénieur civil', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '164', 'profession' : 'Ingénieur du son', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '165', 'profession' : 'Joaillier-joaillière', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '166', 'profession' : 'Kinésithérapeute pédiatrique', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '167', 'profession' : 'Libraire ancien', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '168', 'profession' : 'Maître-nageur', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '169', 'profession' : 'Maquilleur', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '170', 'profession' : 'Maraîcher', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '171', 'profession' : 'Médecin légiste', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '172', 'profession' : 'Météorologiste', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '173', 'profession' : 'Naturopathe', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '174', 'profession' : 'Nutritionniste', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '175', 'profession' : 'Opérateur de télécommunication', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '176', 'profession' : 'Ostéopathe', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '177', 'profession' : 'Paysagiste d\'intérieur', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '178', 'profession' : 'Pharmacien hospitalier', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '179', 'profession' : 'Photographe de mode', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '180', 'profession' : 'Physicien nucléaire', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '181', 'profession' : 'Pilote de ligne commercial', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '182', 'profession' : 'Pilote de sous-marin', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '183', 'profession' : 'Plâtrier-plaquiste', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '184', 'profession' : 'Plongeur professionnel', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '185', 'profession' : 'Podologue du sport', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '186', 'profession' : 'Poissonnier-traiteur', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '187', 'profession' : 'Pompier forestier', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '188', 'profession' : 'Psychologue du travail', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '189', 'profession' : 'Radiologue interventionnel', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '190', 'profession' : 'Réalisateur de documentaire', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '191', 'profession' : 'Scénariste de jeux vidéo', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '192', 'profession' : 'Skipper de course', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '193', 'profession' : 'Sociologue urbain', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '194', 'profession' : 'Sommelier de bière', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '195', 'profession' : 'Soudeur d\'aluminium', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '196', 'profession' : 'Styliste de mode', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '197', 'profession' : 'Tailleur de pierre tombale', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '198', 'profession' : 'Technicien de laboratoire', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '199', 'profession' : 'Urbaniste paysagiste', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '200', 'profession' : 'Vendeur de meubles', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '201', 'profession' : 'Viticulteur bio', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '202', 'profession' : 'Zoologiste marin', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '203', 'profession' : 'Aérodynamicien', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '204', 'profession' : 'Aide-soignant en gériatrie', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '205', 'profession' : 'Architecte d\'intérieur', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '206', 'profession' : 'Astronome planétaire', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '207', 'profession' : 'Bibliothécaire universitaire', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '208', 'profession' : 'Boulanger-pâtissier bio', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '209', 'profession' : 'Cancérologue pédiatrique', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '210', 'profession' : 'Charpentier de marine', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '211', 'profession' : 'Chef de projet web', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '212', 'profession' : 'Chef glacier', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '213', 'profession' : 'Chiropraticien pédiatrique', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '214', 'profession' : 'Chorégraphe de danse contemporaine', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '215', 'profession' : 'Cinéaste indépendant', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '216', 'profession' : 'Comédien de doublage', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '217', 'profession' : 'Consultant en ressources humaines', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '218', 'profession' : 'Danseur contemporain', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '219', 'profession' : 'Dentiste prothésiste', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '220', 'profession' : 'Designer textile', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '221', 'profession' : 'Éclairagiste', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '222', 'profession' : 'Écrivain public', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '223', 'profession' : 'Électricien éolien', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '224', 'profession' : 'Électricien solaire', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '225', 'profession' : 'Électronicien de marine', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '226', 'profession' : 'Facteur d\'orgues', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '227', 'profession' : 'Fleuriste en fleurs séchées', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '228', 'profession' : 'Frigoriste industriel', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '229', 'profession' : 'Garde-rivière', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '230', 'profession' : 'Géotechnicien', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '231', 'profession' : 'Guide de plongée', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '232', 'profession' : 'Hydrologue', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '233', 'profession' : 'Ingénieur agricole', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '234', 'profession' : 'Ingénieur chimiste', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '235', 'profession' : 'Ingénieur en télécommunications', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '236', 'profession' : 'Joaillier-créateur', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '237', 'profession' : 'Kinésithérapeute sportif', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '238', 'profession' : 'Libraire de livres anciens', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '239', 'profession' : 'Maître de cérémonie', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '240', 'profession' : 'Maquilleur de cinéma', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '241', 'profession' : 'Maraudeur social', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '242', 'profession' : 'Médecin humanitaire', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '243', 'profession' : 'Météorologiste de l\'aviation', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '244', 'profession' : 'Naturopathe holistique', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '245', 'profession' : 'Nutritionniste sportif', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '246', 'profession' : 'Ophtalmologiste', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '247', 'profession' : 'Ostéopathe animalier', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '248', 'profession' : 'Paysagiste urbain', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '249', 'profession' : 'Pharmacien industriel', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '250', 'profession' : 'Photographe de mariage', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '251', 'profession' : 'Physicien quantique', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '252', 'profession' : 'Pilote d\'hélicoptère', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '253', 'profession' : 'Plâtrier-stucateur', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '254', 'profession' : 'Plongeur en eaux vives', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '255', 'profession' : 'Podologue pédiatrique', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '256', 'profession' : 'Poissonnier écailler', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '257', 'profession' : 'Pompier de secours', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '258', 'profession' : 'Psychomotricien', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '259', 'profession' : 'Radiologue pédiatrique', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '260', 'profession' : 'Réalisateur de publicités', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '261', 'profession' : 'Scénariste de bandes dessinées', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '262', 'profession' : 'Skipper transatlantique', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '263', 'profession' : 'Sociologue de l\'environnement', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '264', 'profession' : 'Sommelier de thé', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '265', 'profession' : 'Soudeur sous-marin', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '266', 'profession' : 'Styliste d\'intérieur', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '267', 'profession' : 'Tailleur de pierre tombale funéraire', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '268', 'profession' : 'Technicien de maintenance informatique', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '269', 'profession' : 'Urbaniste en développement durable', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '270', 'profession' : 'Vendeur de bijoux', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '271', 'profession' : 'Viticulteur de vin naturel', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '272', 'profession' : 'Zoologiste de la faune sauvage', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '273', 'profession' : 'Aéronaute', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '274', 'profession' : 'Aide-vétérinaire', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '275', 'profession' : 'Architecte naval', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '276', 'profession' : 'Astronome professionnel', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '277', 'profession' : 'Bibliothécaire municipal', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '278', 'profession' : 'Boulanger-pâtissier bio', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '279', 'profession' : 'Cancérologue radiothérapeute', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '280', 'profession' : 'Charpentier métallique', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '281', 'profession' : 'Chef de projet énergies renouvelables', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '282', 'profession' : 'Chef pâtissier', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '283', 'profession' : 'Chiropraticien sportif', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '284', 'profession' : 'Chorégraphe de ballet', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '285', 'profession' : 'Cinéaste documentariste', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '286', 'profession' : 'Comédien de théâtre', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '287', 'profession' : 'Consultant en sécurité informatique', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '288', 'profession' : 'Danseur hip-hop', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '289', 'profession' : 'Dentiste orthodontiste', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '290', 'profession' : 'Designer de jeux vidéo', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '291', 'profession' : 'Écrivain de science-fiction', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '292', 'profession' : 'Électricien éolien offshore', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '293', 'profession' : 'Électricien solaire photovoltaïque', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '294', 'profession' : 'Facteur de clavecins', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '295', 'profession' : 'Fleuriste en ligne de mariage', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '296', 'profession' : 'Frigoriste automobile', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '297', 'profession' : 'Garde-frontière', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '298', 'profession' : 'Géologue de terrain', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '299', 'profession' : 'Guide de safari en Afrique', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '300', 'profession' : 'Hydrologue fluvial', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '301', 'profession' : 'Ingénieur biomédical', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '302', 'profession' : 'Ingénieur en énergie nucléaire', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '303', 'profession' : 'Ingénieur en réalité virtuelle', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '304', 'profession' : 'Joaillier haute joaillerie', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '305', 'profession' : 'Kinésithérapeute respiratoire', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '306', 'profession' : 'Libraire spécialisé en BD', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '307', 'profession' : 'Maître-nageur sauveteur', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '308', 'profession' : 'Maquilleur de théâtre', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '309', 'profession' : 'Marin-pêcheur', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '310', 'profession' : 'Médecin de médecine tropicale', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '311', 'profession' : 'Météorologiste de l\'environnement', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '312', 'profession' : 'Naturopathe en pédiatrie', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '313', 'profession' : 'Nutritionniste en périnatalité', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '314', 'profession' : 'Ophtalmologiste pédiatrique', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '315', 'profession' : 'Ostéopathe équin', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '316', 'profession' : 'Paysagiste de toit vert', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '317', 'profession' : 'Pharmacien hospitalier clinicien', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '318', 'profession' : 'Photographe animalier', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '319', 'profession' : 'Physicien des particules', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '320', 'profession' : 'Pilote de montgolfière', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '321', 'profession' : 'Plâtrier-plaquiste en restauration', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '322', 'profession' : 'Plongeur archéologue', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '323', 'profession' : 'Podologue du sport pédiatrique', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '324', 'profession' : 'Poissonnier-traiteur bio', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '325', 'profession' : 'Pompier de haute montagne', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '326', 'profession' : 'Psychologue de la santé mentale', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '327', 'profession' : 'Radiologue musculo-squelettique', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '328', 'profession' : 'Réalisateur de séries télévisées', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '329', 'profession' : 'Scénariste de romans', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '330', 'profession' : 'Skipper de voile océanique', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '331', 'profession' : 'Sociologue de la mode', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '332', 'profession' : 'Sommelier de café', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '333', 'profession' : 'Soudeur de pipelines', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '334', 'profession' : 'Styliste de costumes', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '335', 'profession' : 'Tailleur de pierre funéraire', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '336', 'profession' : 'Technicien de maintenance éolienne', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '337', 'profession' : 'Urbaniste en mobilité urbaine', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '338', 'profession' : 'Vendeur de montres de luxe', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '339', 'profession' : 'Viticulteur en biodynamie', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '340', 'profession' : 'Zoologiste de la conservation', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '341', 'profession' : 'Agent de voyages', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '342', 'profession' : 'Aide-soignant en psychiatrie', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '343', 'profession' : 'Architecte de paysage', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '344', 'profession' : 'Astronome observateur', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '345', 'profession' : 'Bibliothécaire hospitalier', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '346', 'profession' : 'Boulanger-pâtissier vegan', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '347', 'profession' : 'Cancérologue thoracique', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '348', 'profession' : 'Charpentier traditionnel', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '349', 'profession' : 'Chef de projet environnemental', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '350', 'profession' : 'Chef sushi', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '351', 'profession' : 'Chiropraticien pédiatrique sportif', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '352', 'profession' : 'Chorégraphe de danse classique', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '353', 'profession' : 'Cinéaste indépendant documentaire', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '354', 'profession' : 'Comédien de stand-up', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '355', 'profession' : 'Consultant en développement personnel', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '356', 'profession' : 'Danseur de danse contemporaine', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '357', 'profession' : 'Dentiste pédiatrique spécialisé', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '358', 'profession' : 'Designer de mode éthique', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '359', 'profession' : 'Éducateur canin', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '360', 'profession' : 'Électricien de réseau électrique', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '361', 'profession' : 'Électricien solaire thermique', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '362', 'profession' : 'Facteur de pianos', 'created_at' : 'null', 'updated_at' : 'null'},
           {'id_profession' : '363', 'profession' : 'Fleuriste évén', 'created_at' : 'null', 'updated_at' : 'null'},

        ]
# Code pour générer les UUIDs
for record in VilleRecords:
    record['uuid'] = str(uuid.uuid4())

# Écrire le tableau dans un fichier JSON
with open('ProfesionsRecord_with_uuid.json', 'w') as json_file:
    json.dump(VilleRecords, json_file, indent=4, ensure_ascii=False)

print('Fichier JSON généré avec succès : ProfesionsRecord_with_uuid.json')
